version: '3'
services:

  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: "confluentinc/cp-kafka:5.2.1"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: 'postgres:alpine'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres

  keycloak:
    image: jboss/keycloak
    ports:
      - 18443:8443
      - 18080:8080
      - 19990:9990
    depends_on:
      # Just a delay to wait for postgres! This is not recommended!
      - grafana
      - prometheus
      - jaeger
      - kafka
      - zookeeper
      - transacoes
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      POSTGRES_PORT_5432_TCP_ADDR: 127.0.0.1
      KEYCLOAK_FRONTEND_URL: http://keycloak:8080/auth

  transacoes:
    image: 'zupacademy/transacoes'
    ports:
      - 7777:7777
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 7777
      LOG_LEVEL: INFO
      KAFKA_HOST: "kafka:29092"
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      TRANSACTION_DELAY: 30000

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  prometheus:
    image: prom/prometheus
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
     - prometheus-volume:/etc/prometheus/
    network_mode: bridge
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-volume:/var/lib/grafana
    network_mode: bridge
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  vault:
    image: vault:1.5.3
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_TOKEN: ee413645-dbe8-4848-afc6-6bb2768ada75
      VAULT_ADDR: http://127.0.0.1:8200

  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
          - 3366:3306
            
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_transacao
  
  api-consulta-transacoes:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: api-consulta-transacoes
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - transacoes
      - zookeeper
      - kafka
      - keycloak
    environment:
      KAFKA_HOST: "kafka:29092"
      KAFKA_CONSUMER_GROUP_ID: minha-aplicacao
      KAFKA_AUTO-OFFSET-RESET: latest
      KAFKA_TOPIC: transacoes
      MYSQL_URL: jdbc:mysql://mysql/db_transacao
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/auth/realms/api-transacao
      KEYCLOAK_JWKS_URI: http://keycloak:8080/auth/realms/api-transacao/protocol/openid-connect/certs
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

volumes:
  grafana-volume:
  prometheus-volume:
  postgres-volume:
  mysql-volume: